export const SAVE_CREATE = 'SAVE_CREATE_BUSI_DOMAIN';

export const SAVE_CREATE_PARAMS = 'SAVE_CREATE_PARAMS_BUSI_DOMAIN';

export const INIT_CREATE_PARAMS = 'INIT_CREATE_PARAMS_BUSI_DOMAIN';

export const SAVE_TABLE = 'SAVE_TABLE_BUSI_DOMAIN';

export const SAVE_SEARCH_PARAMS = 'SAVE_SEARCH_PARAMS_BUSI_DOMAIN';

export const SAVE_CONFIG_LIST = 'SAVE_CONFIG_LIST_BUSI_DOMAIN';
