export const SAVE_CREATE = 'SAVE_CREATE_BUSI_VERSION';

export const SAVE_CREATE_PARAMS = 'SAVE_CREATE_PARAMS_BUSI_VERSION';

export const INIT_CREATE_PARAMS = 'INIT_CREATE_PARAMS_BUSI_VERSION';

export const SAVE_TABLE = 'SAVE_TABLE_BUSI_VERSION';

export const SAVE_SEARCH_PARAMS = 'SAVE_SEARCH_PARAMS_BUSI_VERSION';

export const SAVE_USAGE = 'SAVE_USAGE_BUSI_VERSION';

export const SAVE_DOMAIN_LIST = 'SAVE_DOMAIN_LIST_BUSI_VERSION';
