export const SAVE_CREATE = 'SAVE_CREATE_BUSI_VERSION';

export const SAVE_CREATE_PARAMS = 'SAVE_CREATE_PARAMS_BUSI_VERSION';

export const INIT_CREATE_PARAMS = 'INIT_CREATE_PARAMS_BUSI_VERSION';

export const SAVE_TABLE = 'SAVE_TABLE_BUSI_VERSION';

export const SAVE_SEARCH_PARAMS = 'SAVE_SEARCH_PARAMS_BUSI_VERSION';
