export const SAVE_CREATE = 'SAVE_CREATE_SERVICE';

export const SAVE_CREATE_PARAMS = 'SAVE_CREATE_PARAMS_SERVICE';

export const INIT_CREATE_PARAMS = 'INIT_CREATE_PARAMS_SERVICE';

export const SAVE_TABLE = 'SAVE_TABLE_SERVICE';

export const SAVE_SEARCH_PARAMS = 'SAVE_SEARCH_PARAMS_SERVICE';

export const SAVE_CREATE_ENV = 'SAVE_CREATE_ENV_DISPATCHER_SERVICE';

export const SAVE_CREATE_ENV_PARAMS = 'SAVE_CREATE_ENV_PARAMS_SERVICE';

export const INIT_CREATE_ENV_PARAMS = 'INIT_CREATE_ENV_PARAMS_SERVICE';

export const SAVE_ENVLIST = 'SAVE_ENVLIST_SERVICE';
