export const SAVE_CREATE_PRODUCT = 'SAVE_CREATE_PRODUCT_PEODUCT_DETAIL';

export const SAVE_CREATE_PRODUCT_PARAMS = 'SAVE_CREATE_PRODUCT_PARAMS_PEODUCT_DETAIL';

export const INIT_CREATE_PRODUCT_PARAMS = 'INIT_CREATE_PRODUCT_PARAMS_PEODUCT_DETAIL';

export const SAVE_DOMAIL = 'SAVE_DOMAIL_PEODUCT_DETAIL';
