export const SAVE_CREATE = 'SAVE_CREATE_LONG_LINK';

export const SAVE_CREATE_PARAMS = 'SAVE_CREATE_PARAMS_LONG_LINK';

export const INIT_CREATE_PARAMS = 'INIT_CREATE_PARAMS_LONG_LINK';

export const SAVE_TABLE = 'SAVE_TABLE_LONG_LINK';

export const SAVE_SEARCH_PARAMS = 'SAVE_SEARCH_PARAMS_LONG_LINK';

export const SAVE_CONFIG_LIST = 'SAVE_CONFIG_LIST_LONG_LINK';
