export const SAVE_CREATE = 'SAVE_CREATE_PEODUCT_DETAIL';

export const SAVE_CREATE_PRODUCT = 'SAVE_CREATE_PRODUCT_PEODUCT_DETAIL';

export const SAVE_CREATE_TAB = 'SAVE_CREATE_TAB_PEODUCT_DETAIL';

export const SAVE_CREATE_PARAMS = 'SAVE_CREATE_PARAMS_PEODUCT_DETAIL';

export const SAVE_CREATE_PRODUCT_PARAMS = 'SAVE_CREATE_PRODUCT_PARAMS_PEODUCT_DETAIL';

export const INIT_CREATE_PARAMS = 'INIT_CREATE_PARAMS_PEODUCT_DETAIL';

export const INIT_CREATE_PRODUCT_PARAMS = 'INIT_CREATE_PRODUCT_PARAMS_PEODUCT_DETAIL';

export const SAVE_TABLE = 'SAVE_TABLE_PEODUCT_DETAIL';

export const SAVE_SEARCH_PARAMS = 'SAVE_SEARCH_PARAMS_PEODUCT_DETAIL';

export const SAVE_INFO = 'SAVE_INFO_PEODUCT_DETAIL';

export const SAVE_TAB_LIST = 'SAVE_TAB_LIST_PEODUCT_DETAIL';

export const SAVE_ACCESS_LIST = 'SAVE_ACCESS_LIST_PEODUCT_DETAIL';

export const SAVE_DOMAIL = 'SAVE_DOMAIL_PEODUCT_DETAIL';
