export const SAVE_TABLE = 'SAVE_TABLE_OVERVIEW';

export const SAVE_SEARCH_PARAMS = 'SAVE_SEARCH_PARAMS_OVERVIEW';

export const SAVE_ALL_TABLE = 'SAVE_All_TABLE_OVERVIEW';

export const SAVE_ALL_SEARCH_PARAMS = 'SAVE_ALL_SEARCH_PARAMS_OVERVIEW';
