export const SAVE_CREATE = 'SAVE_CREATE_DISPATCHER';

export const SAVE_CREATE_PARAMS = 'SAVE_CREATE_PARAMS_DISPATCHER';

export const INIT_CREATE_PARAMS = 'INIT_CREATE_PARAMS_DISPATCHER';

export const SAVE_CREATE_ENV = 'SAVE_CREATE_ENV_DISPATCHER';

export const SAVE_TABLE = 'SAVE_TABLE_DISPATCHER';

export const SAVE_SEARCH_PARAMS = 'SAVE_SEARCH_PARAMS_DISPATCHER';

export const SAVE_ENVLIST = 'SAVE_ENVLIST_DISPATCHER';

export const SAVE_CONFIG = 'SAVE_CONFIG_DISPATCHER';
